version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: student-postgres
    environment:
      POSTGRES_DB: StudentFinal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Preethu$123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: student-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/StudentFinal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Preethu$123

volumes:
  pgdata:
